src:
  - changed-files:
      - any-glob-to-any-file: src/cpp/**/*

tests:
  - changed-files:
      - any-glob-to-any-file: tests/**/*

JSON:
  - changed-files:
      - any-glob-to-any-file: data/**/*

mods:
  - changed-files:
      - any-glob-to-any-file: data/mods/**/*

translation:
  - changed-files:
      - any-glob-to-any-file: lang/**/*

docs:
  - changed-files:
      - any-glob-to-any-file: docs/**/*

scripts:
  - changed-files:
      - any-glob-to-any-file: scripts/**/*

lua:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.lua"
          - src/cpp/catalua*.cpp
          - src/cpp/catalua*.h
